import Phaser from 'phaser';
import {Capacitor} from '@capacitor/core';
import {App} from '@capacitor/app';
import {Filesystem,Directory,Encoding} from '@capacitor/filesystem';
import {Share} from '@capacitor/share';
import {Haptics,ImpactStyle} from '@capacitor/haptics';
import {ArcadeRun} from './arcade-run';
import {MobileRenderer} from './mobile-renderer';
import {type Mode, type Point} from './game-state';
import {freshProfile,loadProfile,settle,buildStats,runes,modeNames,upgradeCost,buyUpgrade,achievements,claimAchievement,makeChallengeCode,parseChallengeCode,type RuneId,type RunResult,type Profile} from './progression';
import {furniture,interiorStats,type Furniture} from './interior';
import './mobile.css';

type Tab='play'|'build'|'quests'|'records'|'settings';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const escape=(s:string)=>s.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]!));
const text=(id:string,s:string)=>{if($(id)?.textContent!==s)$(id).textContent=s;};
let storageError=false;let profile:Profile;try{profile=loadProfile(localStorage.getItem('playroom-profile-v2'));}catch{profile=freshProfile();storageError=true;}
let mode:Mode='defense',stage=1,tab:Tab='play',risk=false,paused=false,selectedSocket=0,selectedFurniture:Furniture='seat';
let run=new ArcadeRun(mode,stage,profile),resultShown=false,scene:MobileScene|undefined,controlsSignature='',panelSignature='',stick:Point={x:0,y:0};
let audio:AudioContext|undefined,lastSound=0,noticeTimer:ReturnType<typeof setTimeout>|undefined;
const symbols:Record<Mode,string>={defense:'♜',hunt:'✧',landlord:'▥'};
function save(){try{localStorage.setItem('playroom-profile-v2',JSON.stringify(profile));}catch{storageError=true;toast('저장 공간을 사용할 수 없어요. 설정에서 기록을 내려받아 주세요.');}}
function toast(message:string){text('toast',message);$('toast').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('toast').hidden=true,3200);}
function sound(kind:'coin'|'hit'|'upgrade'){
 if(!profile.settings.sound)return;audio??=new AudioContext();if(audio.state==='suspended')void audio.resume();const now=audio.currentTime;if(now-lastSound<.06)return;lastSound=now;const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type=kind==='hit'?'triangle':'sine';o.frequency.setValueAtTime(kind==='coin'?820:kind==='upgrade'?550:160,now);o.frequency.exponentialRampToValueAtTime(kind==='upgrade'?1100:kind==='hit'?65:1200,now+.12);g.gain.setValueAtTime(.1*profile.settings.volume,now);g.gain.exponentialRampToValueAtTime(.001,now+.16);o.start(now);o.stop(now+.17);
}
function connectRun(){run.sound=sound;}connectRun();
$('app').innerHTML=`<aside class="desktop-intro"><a href="/showroom.html" class="back-showroom">← 첫 비교 쇼룸</a><p class="overline">PLAYROOM / MOBILE LAB 02</p><h1>고르고.<br>해내고.<br><em>더 높이.</em></h1><p>조합을 바꿔 한 번 더.<br>어제의 기록을 넘는 작은 도전.</p><div class="desktop-loop"><span>조합의 선택</span><i>↓</i><span>90초의 집중</span><i>↓</i><span>성취와 다음 도전</span></div><p class="desktop-footnote">세로 화면에서 직접 플레이하세요.<br>진행·공간·기록은 이 기기에 저장됩니다.</p></aside>
<div class="phone-shell"><div class="mobile-app"><header class="app-header"><button id="home" class="app-brand" aria-label="도전 화면">▦ <span>플레이룸<small>CHALLENGE CLUB</small></span></button><div class="header-right"><span class="wallet">✦ <b id="wallet">0</b></span><button id="quick-settings" aria-label="설정 열기">⚙</button></div></header>
<nav class="world-switch" aria-label="게임 선택">${(['defense','hunt','landlord'] as Mode[]).map(m=>`<button data-world="${m}" aria-pressed="${m===mode}"><span>${symbols[m]}</span>${modeNames[m]}</button>`).join('')}</nav>
<main class="app-content"><section id="play-view" class="view play-view" aria-label="도전"><div class="mission-line"><div><span id="stage-label">CH.01</span><strong id="mission-title">첫 번째 방어선</strong></div><button id="pause-run" aria-label="일시정지">Ⅱ</button></div><div class="run-hud"><span><small id="progress-label">처치</small><b id="progress-value">0/13</b></span><span><small>정밀</small><b id="perfect-value">0/1</b></span><span><small id="health-label">체력</small><b id="health-value">20</b></span><span class="timer"><small>남은 시간</small><b id="remaining-time">01:30</b></span></div>
<div id="world-container"><div id="mobile-game" tabindex="0" role="application" aria-label="세로형 게임 화면"></div><div id="joystick" hidden aria-label="가상 조이스틱"><span></span></div><div id="run-overlay" class="run-overlay"></div></div>
<div class="play-controls"><div id="resource-line"><span>이번 도전 <b id="run-money">185 G</b></span><span id="run-build">공명 ×1.40</span></div><div id="run-actions" class="run-actions"></div><div class="precision-row"><div class="timing-box"><div class="timing-label"><b id="skill-label">집중 포격</b><span id="timing-caption">중앙에서 탭 · PERFECT ×2</span></div><div class="timing-track"><i class="good-zone"></i><i id="perfect-zone"></i><i id="timing-needle"></i></div></div><button id="skill-button" aria-label="타이밍 스킬 발동">발동 <small>SPACE</small></button></div><p id="run-hint">타워를 고르고 터를 탭하세요.</p></div></section>
<section id="panel-view" class="view panel-view" hidden></section></main>
<nav class="bottom-nav" aria-label="앱 메뉴">${([['play','◈','도전'],['build','⬡','조합'],['quests','⚑','과제'],['records','♧','기록'],['settings','⚙','설정']] as const).map(([id,icon,label])=>`<button data-tab="${id}" aria-current="${id==='play'?'page':'false'}"><span>${icon}</span>${label}</button>`).join('')}</nav><div id="toast" class="toast" role="status" hidden></div></div></div><dialog id="confirm-dialog"><h2>이 기기의 기록을 초기화할까요?</h2><p>성장, 공간, 친구 기록을 모두 지웁니다. 기존 비교 쇼룸 메모는 유지됩니다.</p><div><button id="cancel-reset">취소</button><button id="confirm-reset">초기화</button></div></dialog>`;

// VisualViewport also covers keyboards that resize only the visible viewport (iOS).
function syncMobileViewport(){
 const viewport=window.visualViewport;
 const editing=document.activeElement instanceof HTMLTextAreaElement;
 document.querySelector('.mobile-app')?.classList.toggle('keyboard-open',editing);
 if(!viewport||viewport.scale!==1)return;
 document.documentElement.style.setProperty('--mobile-viewport-height',viewport.height+'px');
 document.documentElement.style.setProperty('--mobile-viewport-top',(editing?viewport.offsetTop:0)+'px');
 if(editing)requestAnimationFrame(()=>{
  const target=document.activeElement?.id==='friend-code'?$('friend-entry'):document.activeElement;
  target?.scrollIntoView({block:'nearest',behavior:'instant'});
 });
}
window.visualViewport?.addEventListener('resize',syncMobileViewport);
window.visualViewport?.addEventListener('scroll',syncMobileViewport);
window.addEventListener('resize',syncMobileViewport);
document.addEventListener('focusin',syncMobileViewport);
document.addEventListener('focusout',()=>requestAnimationFrame(syncMobileViewport));
syncMobileViewport();

function makeRun(){run=new ArcadeRun(mode,stage,profile,risk);connectRun();paused=false;resultShown=false;controlsSignature='';panelSignature='';sync();}
function world(next:Mode){if(run.started&&!run.result){toast('진행 중인 도전을 마치거나 포기한 뒤 세계를 바꿔주세요.');return;}mode=next;stage=Math.min(stage,profile.unlocked[mode]);makeRun();renderPanel();}
function navigate(next:Tab){if(next!=='play'&&run.started&&!run.result)paused=true;tab=next;$('play-view').hidden=next!=='play';$('panel-view').hidden=next==='play';document.querySelectorAll<HTMLElement>('[data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===next?'page':'false'));if(next!=='play')renderPanel();else{requestAnimationFrame(()=>scene?.scale.refresh());sync();}}
function overlay(){let html='';
 if(run.result){const r=run.result;html=`<div class="result-card"><p class="overline">${r.success?'CHALLENGE COMPLETE':'GOOD TRY. GO AGAIN.'}</p><div class="grade grade-${r.grade}">${r.grade}</div><h2>${r.success?'한 단계 더 높이!':'다음엔 더 잘할 수 있어요'}</h2><p>정밀 ${r.perfects} / ${r.attempts} · 최대 ${r.maxCombo}연속 · ${r.elapsed}초</p><strong class="reward-total">✦ +${r.reward}</strong><small>기본 ${r.baseReward} × 등급 ${r.gradeMultiplier.toFixed(1)} × 조합·성장 ${r.buildMultiplier.toFixed(2)}${r.success?'':' × 목표 달성률'}</small><div class="result-buttons"><button id="next-run" class="gold-button">${r.success&&stage<6?'다음 단계 →':'다시 도전 →'}</button><button id="view-records" class="plain-button">기록 · 자랑하기</button></div></div>`;
 }else if(paused&&run.started){html=`<div class="ready-card"><p class="overline">TAKE YOUR TIME</p><h2>잠시 숨 고르기</h2><p>메뉴를 보는 동안 도전 시간도 멈춥니다.</p><button id="continue-run" class="gold-button">계속 도전</button><button id="abandon-run" class="plain-button">현재 도전 포기</button></div>`;
 }else if(!run.started){const st=run.stats;html=`<div class="ready-card"><p class="overline">${mode==='defense'?'GREENKEEP':mode==='hunt'?'RELIC RUN':'CORNER & CO.'} / STAGE ${String(stage).padStart(2,'0')}</p><h2>${['','첫 번째 돌파','연속의 감각','조합의 발견','한계 너머','집중의 경지','마지막 증명'][stage]}</h2><p>${mode==='landlord'?`매출 ${run.goal}G`:`적 ${run.goal}마리`} + 정밀 스킬 ${run.requiredPerfects}회<br>${run.duration}초 안에 함께 달성하세요.</p><div class="ready-build">${run.build.map(id=>`<span style="--rune:${runes[id].color}">${runes[id].symbol} ${runes[id].value}</span>`).join('<i>+</i>')}<b>= ${st.sum}<small>목표 ${st.target}</small></b></div><div class="ready-detail"><span>조합 보상 ×${st.reward.toFixed(2)}</span><span>${st.exact?'공명 활성':'공명 미달성'}</span></div><button id="start-run" class="gold-button">도전 시작 <span>→</span></button><button id="edit-build" class="plain-button">조합 바꾸기 · ${mode==='landlord'?'공간 꾸미기':'전략 준비'}</button><small class="ready-tip">${mode==='defense'?'서리로 늦추고 포격으로 몰아 잡으세요.':mode==='hunt'?'움직여 거리를 벌리고, 적이 모이면 스킬!':'대기 손님을 직접 응대하면 연속 팁이 쌓여요.'}</small></div>`;}
 const signature=html;if($('run-overlay').dataset.signature===signature)return;$('run-overlay').dataset.signature=signature;$('run-overlay').innerHTML=html;$('run-overlay').hidden=!html;$('play-view').classList.toggle('has-overlay',!!html);$('run-overlay').scrollTop=0;
 if($('start-run'))$('start-run').onclick=()=>{run.started=true;run.status='도전 시작! 목표와 정밀 스킬을 함께 달성하세요.';sound('upgrade');sync();};
 if($('continue-run'))$('continue-run').onclick=()=>{paused=false;sync();};
 if($('abandon-run'))$('abandon-run').onclick=()=>{run.finish(false);complete();};
 if($('edit-build'))$('edit-build').onclick=()=>navigate('build');
 if($('next-run'))$('next-run').onclick=()=>{if(run.result?.success)stage=Math.min(6,stage+1);makeRun();};
 if($('view-records'))$('view-records').onclick=()=>navigate('records');
}
function complete(){if(!run.result||resultShown)return;settle(profile,run.result);save();resultShown=true;sync();}
function renderControls(){let items:{name:string;sub:string;disabled:boolean}[];
 if(mode==='defense')items=[{name:'↟ 화살',sub:'55 G',disabled:false},{name:'◉ 포격',sub:'80 G',disabled:false},{name:'❄ 서리',sub:'70 G',disabled:false}];
 else if(mode==='hunt')items=[{name:'✧ 공격력',sub:'+60%p',disabled:!run.choices},{name:'» 공격속도',sub:'+22%p',disabled:!run.choices},{name:'+ 회복',sub:'체력 +8',disabled:!run.choices}];
 else items=[{name:'♙ 직원',sub:run.staff>=4?'최대':`${90+run.staff*110} G`,disabled:run.staff>=4||run.money<90+run.staff*110},{name:'▥ 증축',sub:run.floors>=4?'최대':`${run.floors*150} G`,disabled:run.floors>=4||run.money<run.floors*150},{name:'↑ 단가',sub:run.shopLevel>=4?'최대':`${run.shopLevel*120} G`,disabled:run.shopLevel>=4||run.money<run.shopLevel*120}];
 const signature=JSON.stringify([items,mode,run.selectedKind,run.started,!!run.result,paused]);if(signature===controlsSignature)return;controlsSignature=signature;
 $('run-actions').innerHTML=items.map((item,i)=>`<button data-run-action="${i}" class="${mode==='defense'&&run.selectedKind===i?'selected':''}" ${item.disabled||!run.started||!!run.result||paused?'disabled':''}><b>${item.name}</b><small>${item.sub}</small></button>`).join('');
 $('run-actions').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{run.action(Number(b.dataset.runAction));sync();});
}
function sync(){text('wallet',profile.coins.toLocaleString());text('stage-label',`CH.${String(stage).padStart(2,'0')}`);text('mission-title',`${modeNames[mode]}${risk?' · 추가 계약':''}`);text('progress-label',mode==='landlord'?'매출':'처치');text('progress-value',`${Math.min(run.goal,run.progress)}/${run.goal}`);text('perfect-value',`${run.perfects}/${run.requiredPerfects}`);text('health-label',mode==='landlord'?'규모':'체력');text('health-value',mode==='landlord'?`${run.floors}층`:`${run.health}`);const remaining=Math.max(0,Math.ceil(run.duration-run.elapsed));text('remaining-time',`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`);text('run-money',`${run.money} G`);text('run-build',`조합 ×${run.stats.reward.toFixed(2)}`);text('skill-label',mode==='defense'?'집중 포격':mode==='hunt'?'회피 · 충격파':'한 번에 응대');text('run-hint',run.choices?'레벨 업! 위의 능력 중 하나를 선택하세요.':run.status);text('timing-caption',run.cooldown>0?`${run.cooldown.toFixed(1)}초 후 다시 발동`:'중앙에서 탭 · PERFECT ×2');$('perfect-zone').style.width=`${run.perfectWidth*200}%`;const skill=$<HTMLButtonElement>('skill-button');skill.disabled=!run.started||paused||!!run.result||run.choices||run.cooldown>0;skill.innerHTML=run.cooldown>0?`${run.cooldown.toFixed(1)}<small>재충전</small>`:'발동<small>SPACE</small>';$('joystick').hidden=mode!=='hunt'||!run.started||!!run.result||paused;document.querySelectorAll<HTMLElement>('[data-world]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.world===mode)));renderControls();overlay();}

function panelHead(kicker:string,title:string,description:string){return `<div class="panel-head"><p class="overline">${kicker}</p><h2>${title}</h2><p>${description}</p></div>`;}
function buildPanel(){const stats=buildStats(profile.build,stage),unlocked=Math.max(...Object.values(profile.unlocked));const interior=interiorStats(profile.interior);
 return panelHead('BUILD YOUR ADVANTAGE','생각한 만큼, 강하게.','세 칸의 합을 목표에 맞추고, 내 플레이에 맞는 효과를 고르세요.')+`<div class="equation-top"><span>${stage}단계 공명 목표</span><b>${stats.target}</b><span>일치 +25% · 서로 다른 룬 +10%</span></div><div class="socket-row">${profile.build.map((id,i)=>`<button class="rune-socket ${selectedSocket===i?'active':''}" data-socket="${i}" style="--rune:${runes[id].color}" aria-label="${i+1}번 슬롯 ${runes[id].name}" aria-pressed="${selectedSocket===i}"><small>SLOT ${i+1}</small><span>${runes[id].symbol}</span><b>${runes[id].name} ${runes[id].value}</b></button>`).join('')}</div><div class="formula ${stats.exact?'resonating':''}"><b>${profile.build.map(id=>runes[id].value).join(' + ')} = ${stats.sum}</b><span>${stats.exact?'공명 성공 +25%':'목표와 일치하면 보상 +25%'}</span></div><p class="section-label">${selectedSocket+1}번 칸에 넣을 룬</p><div class="rune-library">${Object.entries(runes).map(([id,r])=>`<button data-rune="${id}" style="--rune:${r.color}" ${unlocked<r.unlock?'disabled':''}><span>${r.symbol}<b>${r.value}</b></span><div><strong>${r.name}</strong><small>${r.description}</small></div>${unlocked<r.unlock?'<i>잠김</i>':''}</button>`).join('')}</div><div class="build-summary"><div><small>공격력</small><b>×${(stats.power*(1+profile.levels.power*.08)).toFixed(2)}</b></div><div><small>공격 속도</small><b>×${stats.speed.toFixed(2)}</b></div><div><small>조합 보상</small><b>×${stats.reward.toFixed(2)}</b></div></div><p class="explain">${stats.shatter?'불씨 + 서리: 성채에서 둔화 중인 적을 포격하면 피해 ×1.5.':'불씨 + 서리를 함께 넣으면 성채의 빙결 파쇄가 열립니다.'}<br>같은 효과는 더하고, 공격력과 속도는 곱해집니다. ${stats.power.toFixed(2)} × ${stats.speed.toFixed(2)} = 초당 공격 기대치 ×${(stats.power*stats.speed).toFixed(2)}.</p>
 ${mode==='landlord'?`<section class="interior-section"><p class="overline">A PLACE OF YOUR OWN</p><h3>나만의 가게 배치</h3><p class="explain">아래 입구에서 위 카운터까지 통로를 남기세요. 손님이 닿는 좌석과 옆 장식이 수익을 올립니다.</p><div class="theme-row">${(['forest','sunset','ocean'] as const).map((theme,i)=>`<button data-theme-choice="${theme}" class="${theme===profile.theme?'selected':''}">${['숲빛','노을','바다'][i]}</button>`).join('')}</div><div class="interior-grid" data-cafe-theme="${profile.theme}">${profile.interior.map((item,i)=>`<button data-cell="${i}" ${i===1||i===7?'disabled':''} class="furniture-${item} ${interior.reached.has(i)?'reachable':''}" aria-label="${Math.floor(i/3)+1}행 ${i%3+1}열 ${furniture[item].name}"><span>${furniture[item].symbol}</span><small>${i===7?'입구':furniture[item].name}</small></button>`).join('')}</div><div class="furniture-picker">${(['empty','seat','plant','lamp'] as Furniture[]).map(item=>`<button data-furniture="${item}" class="${selectedFurniture===item?'selected':''}">${furniture[item].symbol}<small>${furniture[item].name}</small></button>`).join('')}</div><div class="layout-result ${interior.connected?'':'blocked'}"><b>${interior.connected?'동선 연결':'카운터까지 통로가 막혔어요'}</b><span>좌석 ${interior.seats} · 분위기 ${interior.comfort} · 매출 ×${interior.multiplier.toFixed(2)}</span></div></section>`:''}
 <section class="permanent-section"><h3>성취를 다음 도전의 힘으로</h3>${(['power','fortune'] as const).map((key,i)=>`<div class="upgrade-row"><div><b>${i?'보상 연구':'전투 숙련'} <small>Lv.${profile.levels[key]}/5</small></b><p>${i?'정산 보상 +6% / 레벨 · 카페 매출에도 적용':'공격력 +8% / 레벨 · 세션을 넘어 유지'}</p></div><button data-upgrade="${key}" ${profile.levels[key]>=5||profile.coins<upgradeCost(profile.levels[key])?'disabled':''}>${profile.levels[key]>=5?'최대':`✦ ${upgradeCost(profile.levels[key])}`}</button></div>`).join('')}</section><button id="apply-build" class="gold-button wide">${run.started&&!run.result?'다음 도전부터 적용':'이 조합으로 도전 →'}</button>`;
}
function questsPanel(){return panelHead('A LITTLE HARDER, EVERY TIME','다음 벽을 넘어보세요.','같은 단계에서 기록을 다듬거나, 더 어려운 계약에 도전하세요.')+`<div class="stage-list">${[1,2,3,4,5,6].map(n=>{const locked=n>profile.unlocked[mode],best=profile.history.filter(r=>r.mode===mode&&r.stage===n&&r.success).sort((a,b)=>a.elapsed-b.elapsed)[0];return `<button data-stage="${n}" class="stage-item ${stage===n?'selected':''}" ${locked?'disabled':''}><span class="stage-number">${String(n).padStart(2,'0')}</span><span><b>${['첫 번째 돌파','연속의 감각','조합의 발견','한계 너머','집중의 경지','마지막 증명'][n-1]}</b><small>목표 ${mode==='landlord'?220+n*100:9+n*4}${mode==='landlord'?'G':'처치'} · 정밀 ${1+Math.floor(n/2)}회 · 적 ×${(1+(n-1)*.21).toFixed(2)}</small></span><em>${locked?'잠김':best?best.grade:'→'}</em></button>`;}).join('')}</div><label class="risk-contract" for="risk-mode"><span><b>추가 계약 · 더 빠르게, 더 강하게</b><small>75초 · 목표 +15% · 적 체력 +20% · 정산 +35%</small></span><input type="checkbox" id="risk-mode" ${risk?'checked':''} ${run.started&&!run.result?'disabled':''}></label><div class="grade-guide"><h3>실력은 보상에 어떻게 반영되나요?</h3><p><b>S ×1.8</b> 정밀 비율 65%↑ · 피해/이탈 2↓ · 75초 이내</p><p><b>A ×1.4</b> 정밀 비율 35%↑ · 피해/이탈 6↓</p><p><b>B ×1.0</b> 목표와 정밀 횟수 달성</p><p><b>C ×0.2</b> 미완료 · 목표 달성률만큼 연습 보상</p><small>기본 보상 × 등급 × 조합 × 영구 연구 × 추가 계약</small></div><h3 class="section-title">쌓이는 성취</h3>${achievements.map(a=>{const claimed=profile.claimed.includes(`achievement:${a.id}`),done=a.done(profile);return `<div class="achievement-row"><span class="medal ${done?'earned':''}">✦</span><div><b>${a.name}</b><small>${a.description}</small></div><button data-claim="${a.id}" ${claimed||!done?'disabled':''}>${claimed?'완료':`+${a.reward}`}</button></div>`;}).join('')}`;}
function recordsPanel(){const records=profile.history.filter(r=>r.mode===mode),best=records.filter(r=>r.success).sort((a,b)=>b.stage-a.stage||a.elapsed-b.elapsed)[0];
 return panelHead('SHOW YOUR PROGRESS','잘한 건, 자랑해도 되죠.','내 최고 기록과 공간을 카드로 남기고, 친구의 도전 기록을 가져오세요.')+`<div class="showcase-card" id="showcase-card"><small>${modeNames[mode]} · MY PERSONAL BEST</small><div class="showcase-symbol">${symbols[mode]}</div><h3>${best?`${best.stage}단계 ${best.grade}등급`:'아직 쓰이지 않은 기록'}</h3><p>${best?`${best.elapsed}초 · 정밀 ${best.perfects}회`:'첫 번째 도전으로 나만의 카드를 완성하세요.'}</p><div class="mini-runes">${(best?.build??profile.build).map(id=>`<span style="color:${runes[id].color}">${runes[id].symbol} ${runes[id].value}</span>`).join('')}</div></div><div class="share-buttons"><button id="share-card" ${best||mode==='landlord'?'':'disabled'}>공간·성취 카드 저장 ↗</button><button id="create-code" ${best?'':'disabled'}>친구 도전 코드</button></div><textarea id="challenge-output" readonly hidden aria-label="친구에게 전달할 도전 코드"></textarea><section class="friend-section"><h3>친구의 기록에 도전하기</h3><p class="explain">친구가 보낸 코드를 붙여넣으세요. 기록과 룬 조합을 구경할 수 있습니다. 기기에 저장한 비교 기록이며 서버가 검증한 순위는 아닙니다.</p><div id="friend-entry" class="friend-entry"><label for="friend-code" class="sr-only">친구 도전 코드</label><textarea id="friend-code" rows="2" autocapitalize="off" autocomplete="off" spellcheck="false" placeholder="PLAY2.로 시작하는 코드"></textarea><button id="import-friend" class="plain-button wide">친구 기록 가져오기 +</button></div>${profile.friends.filter(r=>r.mode===mode).map((r,i)=>`<div class="friend-record"><span>♧</span><div><b>${escape(r.name||'친구')} · ${r.stage}단계 ${r.grade}</b><small>${r.elapsed}초 · 정밀 ${r.perfects}회 · ${r.build.map(id=>runes[id].name).join(' + ')}</small></div><button data-friend="${i}">조합 보기</button></div>`).join('')}</section><h3 class="section-title">내 도전 기록 <small>최근 ${records.length}회</small></h3><div class="records-list">${records.length?records.map(r=>`<div class="record-row"><b class="record-grade grade-${r.grade}">${r.grade}</b><div><strong>${r.stage}단계 ${r.success?'돌파':'재도전'}</strong><small>${r.elapsed}초 · 정밀 ${r.perfects}/${r.attempts} · ${r.maxCombo}연속</small></div><em>+${r.reward} ✦</em></div>`).join(''):'<p class="empty-message">도전을 마치면 성장 과정이 여기에 남습니다.</p>'}</div>`;
}
function settingsPanel(){return panelHead('MAKE YOURSELF COMFORTABLE','내 손에 맞게.','화면과 소리, 기록을 관리하세요.')+`<div class="settings-group"><h3>플레이 환경</h3>${([['sound','효과음','공격·획득·정밀 판정 소리'],['haptics','진동 피드백','지원 기기에서 정밀 성공 시 짧게 진동'],['reducedMotion','효과 줄이기','파티클과 장식 애니메이션을 줄입니다']] as const).map(([key,label,desc])=>`<label class="setting-row" for="setting-${key}"><span><b>${label}</b><small>${desc}</small></span><input id="setting-${key}" data-setting="${key}" type="checkbox" ${profile.settings[key]?'checked':''}></label>`).join('')}<label class="setting-row" for="volume"><span><b>효과음 크기</b><small id="volume-value">${Math.round(profile.settings.volume*100)}%</small></span><input id="volume" type="range" min="0" max="100" value="${profile.settings.volume*100}"></label><label class="setting-row" for="fps"><span><b>화면 갱신</b><small>30fps는 배터리 사용을 줄입니다</small></span><select id="fps"><option value="60" ${profile.settings.fps===60?'selected':''}>60fps</option><option value="30" ${profile.settings.fps===30?'selected':''}>30fps</option></select></label></div><div class="settings-group"><h3>기록과 데이터</h3><p class="explain">성장·조합·공간·결과는 이 기기에 저장됩니다. 진행 중인 도전은 결과 정산 시 저장됩니다. 앱 삭제 시 기록이 지워질 수 있습니다.</p><button id="export-profile" class="settings-button">기록 백업 내려받기 ↓</button><button id="reset-profile" class="settings-button danger">이 기기의 진행 초기화</button><p class="storage-state">${storageError?'저장 제한됨 · 백업을 이용하세요':'기기 저장 사용 중'}</p></div><div class="settings-group"><h3>플레이룸 챌린지 0.2</h3><p class="explain">Phaser + TypeScript · Capacitor 모바일 앱<br>온라인 계정·실시간 방문·공식 리더보드는 아직 연결하지 않았습니다.</p><a class="settings-button" href="/showroom.html">이전 비교 쇼룸 보기 →</a></div>`;}

function renderPanel(){if(tab==='play')return;$('panel-view').innerHTML=tab==='build'?buildPanel():tab==='quests'?questsPanel():tab==='records'?recordsPanel():settingsPanel();bindPanel();syncMobileViewport();}
function bindPanel(){
 document.querySelectorAll<HTMLButtonElement>('[data-socket]').forEach(b=>b.onclick=()=>{selectedSocket=Number(b.dataset.socket);renderPanel();});
 document.querySelectorAll<HTMLButtonElement>('[data-rune]').forEach(b=>b.onclick=()=>{profile.build[selectedSocket]=b.dataset.rune as RuneId;save();if(!run.started||run.result)makeRun();renderPanel();});
 document.querySelectorAll<HTMLButtonElement>('[data-upgrade]').forEach(b=>b.onclick=()=>{if(buyUpgrade(profile,b.dataset.upgrade as 'power'|'fortune')){save();sound('upgrade');if(!run.started||run.result)makeRun();renderPanel();text('wallet',String(profile.coins));}});
 document.querySelectorAll<HTMLButtonElement>('[data-stage]').forEach(b=>b.onclick=()=>{if(run.started&&!run.result){toast('현재 도전을 마치거나 포기한 뒤 변경할 수 있어요.');return;}stage=Number(b.dataset.stage);makeRun();navigate('play');});
 document.querySelectorAll<HTMLButtonElement>('[data-claim]').forEach(b=>b.onclick=()=>{if(claimAchievement(profile,b.dataset.claim!)){save();sound('upgrade');renderPanel();text('wallet',String(profile.coins));}});
 document.querySelectorAll<HTMLButtonElement>('[data-theme-choice]').forEach(b=>b.onclick=()=>{profile.theme=b.dataset.themeChoice as Profile['theme'];save();if(!run.started||run.result)makeRun();renderPanel();});
 document.querySelectorAll<HTMLButtonElement>('[data-furniture]').forEach(b=>b.onclick=()=>{selectedFurniture=b.dataset.furniture as Furniture;renderPanel();});
 document.querySelectorAll<HTMLButtonElement>('[data-cell]').forEach(b=>b.onclick=()=>{profile.interior[Number(b.dataset.cell)]=selectedFurniture;save();if(!run.started||run.result)makeRun();renderPanel();});
 if($('apply-build'))$('apply-build').onclick=()=>{if(run.started&&!run.result)toast('변경한 조합과 공간은 다음 도전부터 적용됩니다.');navigate('play');};
 if($('risk-mode'))$<HTMLInputElement>('risk-mode').onchange=()=>{risk=$<HTMLInputElement>('risk-mode').checked;makeRun();renderPanel();};
 document.querySelectorAll<HTMLInputElement>('[data-setting]').forEach(b=>b.onchange=()=>{profile.settings[b.dataset.setting as 'sound'|'haptics'|'reducedMotion']=b.checked;save();if(b.dataset.setting==='sound')sound('upgrade');});
 if($('volume'))$<HTMLInputElement>('volume').oninput=()=>{profile.settings.volume=Number($<HTMLInputElement>('volume').value)/100;text('volume-value',`${Math.round(profile.settings.volume*100)}%`);save();};
 if($('fps'))$<HTMLSelectElement>('fps').onchange=()=>{profile.settings.fps=Number($<HTMLSelectElement>('fps').value) as 30|60;save();};
 if($('reset-profile'))$('reset-profile').onclick=()=>$<HTMLDialogElement>('confirm-dialog').showModal();
 if($('export-profile'))$('export-profile').onclick=()=>void exportProfile();
 if($('share-card'))$('share-card').onclick=()=>void shareCard();
 if($('create-code'))$('create-code').onclick=()=>{const best=profile.history.filter(r=>r.mode===mode&&r.success).sort((a,b)=>b.stage-a.stage||a.elapsed-b.elapsed)[0];if(!best)return;const code=makeChallengeCode({name:'도전자',mode,stage:best.stage,grade:best.grade,elapsed:best.elapsed,perfects:best.perfects,build:best.build});const out=$<HTMLTextAreaElement>('challenge-output');out.hidden=false;out.value=code;out.select();toast('코드를 복사해 친구에게 전달하세요.');};
 if($('import-friend'))$('import-friend').onclick=()=>{const record=parseChallengeCode($<HTMLTextAreaElement>('friend-code').value.trim());if(!record){toast('올바른 PLAY2. 도전 코드를 입력하세요.');return;}if(profile.friends.some(r=>JSON.stringify(r)===JSON.stringify(record))){toast('이미 가져온 기록입니다.');return;}profile.friends.unshift(record);profile.friends=profile.friends.slice(0,20);save();renderPanel();toast('친구 기록을 가져왔어요.');};
 document.querySelectorAll<HTMLButtonElement>('[data-friend]').forEach(b=>b.onclick=()=>{const r=profile.friends.filter(r=>r.mode===mode)[Number(b.dataset.friend)];toast(`${r.build.map(id=>`${runes[id].name}(${runes[id].value})`).join(' + ')} · 합 ${buildStats(r.build,r.stage).sum}`);});
}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportProfile(){try{const data=JSON.stringify(profile,null,2);if(Capacitor.isNativePlatform()){const result=await Filesystem.writeFile({path:'playroom-backup.json',data,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:'플레이룸 기록 백업',files:[result.uri]});}else download(new Blob([data],{type:'application/json'}),'playroom-backup.json');}catch{toast('백업을 공유하지 못했습니다. 다시 시도해주세요.');}}
async function shareCard(){const canvas=document.createElement('canvas');canvas.width=840;canvas.height=1140;const c=canvas.getContext('2d')!;c.scale(2,2);c.fillStyle='#17373f';c.fillRect(0,0,420,570);c.font='700 24px sans-serif';c.fillStyle='#f4db9d';c.fillText('나의 플레이룸',26,43);c.font='14px sans-serif';c.fillStyle='#bfd7cc';c.fillText(modeNames[mode],26,72);
 const preview=document.createElement('canvas');preview.width=420;preview.height=350;const painter=new MobileRenderer(preview);painter.height=350;const showcase=new ArcadeRun(mode,stage,profile);if(mode==='landlord'){showcase.floors=Math.max(1,Math.min(4,profile.unlocked.landlord));showcase.staff=2;}else{showcase.grow();}painter.render(showcase);c.drawImage(preview,0,90,420,350);
 const best=profile.history.filter(r=>r.mode===mode&&r.success).sort((a,b)=>b.stage-a.stage||a.elapsed-b.elapsed)[0];c.font='700 25px sans-serif';c.fillStyle='#f3d88c';c.fillText(best?`${best.stage}단계 ${best.grade}등급 · ${best.elapsed}초`:'내가 꾸민 골목상회',26,480);c.font='14px sans-serif';c.fillStyle='#c2d5cb';c.fillText(profile.build.map(id=>`${runes[id].name} ${runes[id].value}`).join(' + '),26,511);c.font='12px sans-serif';c.fillText('PLAYROOM · 기기 저장 기록 / 온라인 인증 아님',26,548);
 const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob){toast('카드를 만들지 못했어요. 다시 시도해주세요.');return;}const file=new File([blob],'my-playroom.png',{type:'image/png'});
 try{if(Capacitor.isNativePlatform()){const data=canvas.toDataURL('image/png').split(',')[1];const result=await Filesystem.writeFile({path:'my-playroom.png',data,directory:Directory.Cache});await Share.share({title:'나의 플레이룸',files:[result.uri]});}else if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'나의 플레이룸'});else download(blob,'my-playroom.png');}catch(e){if(Capacitor.isNativePlatform())toast('공유를 완료하지 못했어요. 다시 시도해주세요.');else if(!(e instanceof Error&&e.name==='AbortError'))download(blob,'my-playroom.png');}
}
document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>navigate(b.dataset.tab as Tab));document.querySelectorAll<HTMLButtonElement>('[data-world]').forEach(b=>b.onclick=()=>world(b.dataset.world as Mode));$('quick-settings').onclick=()=>navigate('settings');$('home').onclick=()=>navigate('play');$('pause-run').onclick=()=>{if(run.started&&!run.result){paused=!paused;sync();}};
function activate(){if(tab!=='play'||paused)return;if(run.activateSkill()&&run.lastJudgment.startsWith('PERFECT')&&profile.settings.haptics){if(Capacitor.isNativePlatform())void Haptics.impact({style:ImpactStyle.Light});else navigator.vibrate?.(20);}sync();}
$('skill-button').onclick=activate;window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!['INPUT','TEXTAREA','BUTTON','SELECT'].includes(document.activeElement?.tagName??'')){e.preventDefault();activate();}});
$('cancel-reset').onclick=()=>$<HTMLDialogElement>('confirm-dialog').close();$('confirm-reset').onclick=()=>{profile=freshProfile();save();stage=1;risk=false;makeRun();renderPanel();$<HTMLDialogElement>('confirm-dialog').close();toast('진행 기록을 초기화했습니다.');};
const joystick=$('joystick');joystick.addEventListener('pointerdown',e=>{joystick.setPointerCapture(e.pointerId);setStick(e);});joystick.addEventListener('pointermove',e=>{if(joystick.hasPointerCapture(e.pointerId))setStick(e);});function setStick(e:PointerEvent){const b=joystick.getBoundingClientRect(),dx=(e.clientX-b.x-b.width/2)/(b.width*.35),dy=(e.clientY-b.y-b.height/2)/(b.height*.35),n=Math.max(1,Math.hypot(dx,dy));stick={x:dx/n,y:dy/n};joystick.querySelector<HTMLElement>('span')!.style.transform=`translate(${stick.x*22}px,${stick.y*22}px)`;}
function clearStick(){stick={x:0,y:0};joystick.querySelector<HTMLElement>('span')!.style.transform='';}joystick.addEventListener('pointerup',clearStick);joystick.addEventListener('pointercancel',clearStick);window.addEventListener('blur',clearStick);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&run.started&&!run.result){paused=true;clearStick();sync();save();}});
if(Capacitor.isNativePlatform()){void App.addListener('appStateChange',({isActive})=>{if(!isActive&&run.started&&!run.result){paused=true;save();sync();}});void App.addListener('backButton',()=>{if(tab!=='play')navigate('play');else if(run.started&&!run.result){paused=true;sync();}else void App.minimizeApp();});}

class MobileScene extends Phaser.Scene {
 surface!:Phaser.Textures.CanvasTexture;picture!:Phaser.GameObjects.Image;painter!:MobileRenderer;keys=new Set<string>();paintTimer=0;uiTimer=0;
 constructor(){super('mobile');}
 create(){scene=this;this.surface=this.textures.createCanvas('portrait',420,460)!;this.painter=new MobileRenderer(this.surface.canvas);this.picture=this.add.image(0,0,'portrait').setOrigin(0);this.resizeWorld();this.scale.on('resize',()=>this.resizeWorld());this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(paused||tab!=='play')return;const point=this.painter.input({x:p.x/this.scale.width*420,y:p.y/this.scale.height*this.painter.height},run);if(point){run.click(point);sync();}});this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{if(mode==='hunt'&&p.isDown&&!paused&&run.started&&!run.result){const point=this.painter.input({x:p.x/this.scale.width*420,y:p.y/this.scale.height*this.painter.height},run);if(point)run.click(point);}});window.addEventListener('keydown',e=>{if(['TEXTAREA','INPUT','SELECT'].includes(document.activeElement?.tagName??''))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){if(tab==='play')e.preventDefault();this.keys.add(e.key.toLowerCase());}});window.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>this.keys.clear());}
 resizeWorld(){if(!this.scale.width||!this.scale.height)return;const h=Math.max(230,Math.round(this.scale.height/this.scale.width*420));this.surface.setSize(420,h);this.painter.height=h;this.painter.displayScale=Math.min(this.scale.width/420,this.scale.height/h);this.picture.setDisplaySize(this.scale.width,this.scale.height);}
 update(_time:number,delta:number){const dt=Math.min(.05,delta/1000);if(!paused&&tab==='play'&&!document.hidden){const typing=['TEXTAREA','INPUT'].includes(document.activeElement?.tagName??'');const x=typing?0:stick.x||Number(this.keys.has('d')||this.keys.has('arrowright'))-Number(this.keys.has('a')||this.keys.has('arrowleft'));const y=typing?0:stick.y||Number(this.keys.has('s')||this.keys.has('arrowdown'))-Number(this.keys.has('w')||this.keys.has('arrowup'));run.update(dt,{x,y});if(run.result)complete();}
  $('timing-needle').style.left=`${run.meter*100}%`;this.paintTimer+=dt;if(tab==='play'&&this.paintTimer>=1/profile.settings.fps){this.painter.reduced=profile.settings.reducedMotion||matchMedia('(prefers-reduced-motion: reduce)').matches;this.painter.render(run);this.surface.refresh();this.paintTimer=0;}this.uiTimer+=dt;if(this.uiTimer>.1){if(tab==='play')sync();this.uiTimer=0;}
 }
}
new Phaser.Game({type:Phaser.AUTO,parent:'mobile-game',width:420,height:460,scene:MobileScene,scale:{mode:Phaser.Scale.RESIZE},backgroundColor:'#324c49',render:{antialias:true},audio:{noAudio:true},banner:false});sync();
